if ($ARGS[0] -eq $null) {return("Params .ini not supplied, please supply a params .ini parameter.")}

.\hobl.cmd -p $ARGS[0] -s charge_on global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s wait_for_dut global:run_type="Misc"
# .\hobl.cmd -p $ARGS[0] -s config_check global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s productivity_prep global:attempts=2 global:run_type="Prep"
.\hobl.cmd -p $ARGS[0] -s abl_active global:tools="+power_light screen_record" global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s recharge global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s abl abl:loops="100" global:rundown_mode=1 global:run_type="Power" global:tools="+power_light auto_charge"
.\hobl.cmd -p $ARGS[0] -s charge_on global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s study_report global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s process_idle_tasks daily_prep:timeout=7200 daily_prep:loops=1 global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s reboot global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s notify global:run_type="Misc"

.\hobl.cmd -p $ARGS[0] -s wait_for_dut global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s recharge global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s web web:loops="100" global:rundown_mode=1 global:stop_soc=0 global:crit_batt_level=3 display_brightness:brightness=150nits global:run_type="Power" global:tools="+power_light auto_charge"
.\hobl.cmd -p $ARGS[0] -s charge_on global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s study_report global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s process_idle_tasks daily_prep:timeout=7200 daily_prep:loops=1 global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s reboot global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s notify global:run_type="Misc"

.\hobl.cmd -p $ARGS[0] -s wait_for_dut global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s recharge global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s lvp lvp:duration="1000000" lvp:airplane_mode="0" global:stop_soc=0 global:crit_batt_level=3 global:rundown_mode=1 global:run_type="Power" global:tools="+power_light auto_charge"
.\hobl.cmd -p $ARGS[0] -s charge_on global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s study_report global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s process_idle_tasks daily_prep:timeout=7200 daily_prep:loops=1 global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s reboot global:run_type="Misc"
.\hobl.cmd -p $ARGS[0] -s notify global:run_type="Misc"
