[global]
msa_account=
dut_password=
dut_ip=127.0.0.1
dut_wifi_name=
dut_wifi_password=
charge_off_call=
charge_on_call=
study_type=HOBL
dut_architecture=[DUT_ARCHITECTURE]
windows_version=[WINDOWS_VERSION]_[WINDOWS_BUILD]
result_dir=c:\hobl_results
tools=run_report
prep_tools=screen_record
goals=
post_run_delay=0
local_execution=1
config_check=1
prep_status_enable=0
host_ip=localhost

[display_brightness]
nits_map=[NITS_MAP]

[dut_setup]
reboot_prompt=0
reboot=0
local_setup=1

[office_install]
activate=0

[run_report]
fail_on="Run Start Audio Volume (%) | Run Start Screen Brightness (%) | Run Start Charge State | Run Stop Charge State | Run Stop Battery State (%) | Run Start Battery State (%)"

[study_report]
template=docs\basic_study_report_template.xlsx

; [power_light]
; soc=PM_TOTAL_VCCIN_AUX_IN | PM_TOTAL_VCCIN_IN | PM_TOTAL_+1P8VSUS_ORG_IN
; wifi=PM_TOTAL_3P3V_TOP_IN
; storage=PM_TOTAL_3P3V_SSD
; memory=PM_TOTAL_1P1V_DDR_VDD2_IN
; display=PM_TOTAL_3P3V_PANEL_IN | PM_TOTAL_VSYS_TOP_IN 
; total=PM_TOTAL_BATT